import express, { NextFunction, Request, Response } from "express";
import path from "path";
import fs from "fs";
import crypto from "crypto";
import QRCode from "qrcode";
import AdmZip from "adm-zip";

import { getConfig, updateConfig } from "./src/bot/config.js";
import { getCommandsDir, initRegistry, getCommands, getCommand } from "./src/bot/commandRegistry.js";
import { getBotState, startLiveBot, stopLiveBot, addLog, simulateMessage, clearLogs } from "./src/bot/botEngine.js";
import { getCommandStats } from "./src/bot/commandStats.js";
import { getAIClient, generateTextWithFallback } from "./src/bot/geminiClient.js";
import { compileCommandToMjs } from "./src/bot/commandCompiler.js";
import {
  ALLOWED_SECRET_NAMES,
  isAllowedSecretName,
  getSecretStatus,
  setSecret,
  deleteSecret,
  maskSecret,
} from "./src/bot/secrets.js";

/**
 * Creates the Express application with all /api routes, authentication and
 * rate limiting. The entry point (server.ts) attaches the static/Vite
 * middleware and starts listening — splitting this keeps the API testable.
 */
export function createApp(): express.Express {
  const app = express();
  app.set("trust proxy", true);
  app.use(express.json({ limit: "25mb" }));

  // ---------------------------------------------------------------------------
  // Panel authentication
  // ---------------------------------------------------------------------------
  // A configured PANEL_TOKEN is required for API access. When unset, a random
  // token is generated at startup: the panel itself receives it as an HttpOnly
  // cookie, and it is printed once to the server console for API tooling.
  const configuredToken = process.env.PANEL_TOKEN?.trim() || "";
  const panelToken = configuredToken || crypto.randomBytes(24).toString("hex");
  const tokenIsAutoGenerated = !configuredToken;

  function readCookie(req: Request, name: string): string | null {
    const raw = req.headers.cookie || "";
    for (const part of raw.split(";")) {
      const eq = part.indexOf("=");
      if (eq === -1) continue;
      const key = part.slice(0, eq).trim();
      if (key === name) {
        try {
          return decodeURIComponent(part.slice(eq + 1).trim());
        } catch {
          return null;
        }
      }
    }
    return null;
  }

  app.use((req: Request, res: Response, next: NextFunction) => {
    if (req.path.startsWith("/api/")) {
      const bearer = (req.headers.authorization || "").replace(/^Bearer\s+/i, "");
      const cookieToken = readCookie(req, "panel_token");
      const authorized = bearer === panelToken || cookieToken === panelToken;

      console.log(`============================= [API Auth Interception] =============================`);
      console.log(`📍 Path: ${req.method} ${req.path}`);
      console.log(`🍪 Raw Cookie Header: "${req.headers.cookie || ""}"`);
      console.log(`🍪 Parsed Cookie 'panel_token': "${cookieToken}"`);
      console.log(`🔑 Authorization Header (Bearer): "${req.headers.authorization || ""}"`);
      console.log(`🔑 Extracted Bearer: "${bearer}"`);
      console.log(`🎯 Expected Server Token: "${panelToken}"`);
      console.log(`🛡️  Is Authorized: ${authorized}`);
      console.log(`📝 Full Headers Context:`, JSON.stringify(req.headers, null, 2));
      console.log(`==================================================================================`);

      if (!authorized) {
        return res.status(401).json({ error: "Unauthorized: a valid PANEL_TOKEN is required to access the bot API." });
      }
    } else {
      // Hand the panel its session token on page loads.
      // Explicitly set 'sameSite: none' and 'secure: true' for ALL environments as requested
      // to guarantee cookies pass through cross-site iFrames in all run configurations.
      res.cookie("panel_token", panelToken, {
        httpOnly: true,
        sameSite: "none",
        secure: true,
        maxAge: 365 * 24 * 60 * 60 * 1000,
      });
    }
    next();
  });

  if (tokenIsAutoGenerated) {
    console.log(`🔑 Panel API token (auto-generated): ${panelToken}`);
    console.log("   Set the PANEL_TOKEN environment variable to use a token of your choice.");
  }

  // ---------------------------------------------------------------------------
  // Rate limiting (in-memory fixed window)
  // ---------------------------------------------------------------------------
  const buckets = new Map<string, { count: number; resetAt: number }>();

  function rateLimit(max: number, windowMs: number) {
    return (req: Request, res: Response, next: NextFunction) => {
      const key = `${req.path}|${req.ip || "unknown"}`;
      const now = Date.now();
      const bucket = buckets.get(key);
      if (!bucket || bucket.resetAt < now) {
        buckets.set(key, { count: 1, resetAt: now + windowMs });
        return next();
      }
      bucket.count++;
      if (bucket.count > max) {
        return res.status(429).json({ error: "Too many requests. Please slow down and try again shortly." });
      }
      next();
    };
  }

  const generalLimiter = rateLimit(300, 60_000);
  app.use("/api", generalLimiter);

  // Stricter limits for expensive / abuse-prone routes
  app.post("/api/bot/simulate", rateLimit(30, 60_000));
  app.post("/api/bot/commands/save", rateLimit(10, 60_000));
  app.post("/api/bot/commands/generate", rateLimit(10, 60_000));
  app.get("/api/bot/download-zip", rateLimit(5, 60_000));
  app.post("/api/gemini/transcribe", rateLimit(10, 60_000));
  app.post("/api/gemini/voice-conversation", rateLimit(10, 60_000));
  app.post("/api/bot/secrets", rateLimit(10, 60_000));
  app.delete("/api/bot/secrets", rateLimit(10, 60_000));

  // Periodically drop expired buckets so the map cannot grow unbounded.
  const sweepTimer = setInterval(() => {
    const now = Date.now();
    for (const [key, bucket] of buckets) {
      if (bucket.resetAt < now) buckets.delete(key);
    }
  }, 10 * 60 * 1000);
  sweepTimer.unref();

  // ---------------------------------------------------------------------------
  // Configuration helpers
  // ---------------------------------------------------------------------------
  function sanitizeConfig(input: any): Partial<any> {
    const out: any = {};
    if (typeof input?.botName === "string") {
      const name = input.botName.trim().slice(0, 40);
      if (name) out.botName = name;
    }
    if (typeof input?.prefix === "string") {
      const prefix = input.prefix.trim();
      if (!prefix || prefix.length > 2) {
        throw new Error("Prefix must be 1-2 characters long.");
      }
      out.prefix = prefix;
    }
    if (typeof input?.ownerNumber === "string") {
      out.ownerNumber = input.ownerNumber.replace(/[^0-9+]/g, "").slice(0, 16);
    }
    if (typeof input?.botImage === "string" && /^https?:\/\//.test(input.botImage)) {
      out.botImage = input.botImage.slice(0, 500);
    }
    if (typeof input?.newsletterUrl === "string" && /^https?:\/\//.test(input.newsletterUrl)) {
      out.newsletterUrl = input.newsletterUrl.slice(0, 500);
    }
    if (typeof input?.newsletterName === "string") {
      const name = input.newsletterName.trim().slice(0, 60);
      if (name) out.newsletterName = name;
    }
    return out;
  }

  // ---------------------------------------------------------------------------
  // API: Get and Update Configuration
  // ---------------------------------------------------------------------------
  app.get("/auth/token", (req, res) => {
    res.json({ token: panelToken });
  });

  app.get("/api/bot/config", (req, res) => {
    res.json(getConfig());
  });

  app.post("/api/bot/config", (req, res) => {
    try {
      const updated = updateConfig(sanitizeConfig(req.body));
      addLog(`⚙️ Configuration updated from panel: Bot Name: "${updated.botName}", Prefix: "${updated.prefix}"`);
      res.json(updated);
    } catch (error: any) {
      res.status(400).json({ error: error?.message || "Invalid configuration." });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Secrets management (masked — raw values never leave the server)
  // ---------------------------------------------------------------------------
  app.get("/api/bot/secrets", (req, res) => {
    res.json({ secrets: ALLOWED_SECRET_NAMES.map((name) => getSecretStatus(name)) });
  });

  app.post("/api/bot/secrets", (req, res) => {
    const { name, value } = req.body ?? {};
    if (typeof name !== "string" || !isAllowedSecretName(name)) {
      return res.status(400).json({ error: "Unsupported secret name." });
    }
    if (typeof value !== "string" || !value.trim()) {
      return res.status(400).json({ error: "Secret value is required." });
    }
    const clean = value.trim();
    if (clean.length > 2000) {
      return res.status(400).json({ error: "Secret value is too long (max 2000 characters)." });
    }
    if (clean === "MY_GEMINI_API_KEY" || clean === "YOUR_API_KEY_HERE") {
      return res.status(400).json({ error: "That looks like the placeholder value — please paste your real key." });
    }

    const result = setSecret(name, clean);
    addLog(`🔑 Secret "${name}" updated (${maskSecret(clean)}).`);
    res.json({ success: true, name, masked: maskSecret(clean), ...result });
  });

  app.delete("/api/bot/secrets", (req, res) => {
    const { name } = req.body ?? {};
    if (typeof name !== "string" || !isAllowedSecretName(name)) {
      return res.status(400).json({ error: "Unsupported secret name." });
    }
    const result = deleteSecret(name);
    addLog(`🔑 Secret "${name}" removed.`);
    res.json({ success: true, name, ...result });
  });

  // ---------------------------------------------------------------------------
  // API: Download the full project source as a ZIP (for backups/moving).
  // Served through the same authenticated origin as the panel, so it works
  // inside the preview proxy (which injects the traffic token).
  // ---------------------------------------------------------------------------
  app.get("/nebula-bot-latest.zip", (req, res) => {
    const zipPath = path.join(process.cwd(), "nebula-bot-latest.zip");
    if (!fs.existsSync(zipPath)) {
      return res.status(404).json({ error: "Project archive not available on this deployment." });
    }
    res.download(zipPath, "nebula-bot-latest.zip");
  });

  // ---------------------------------------------------------------------------
  // API: Get Connection State & QR Code
  // ---------------------------------------------------------------------------
  app.get("/api/bot/status", (req, res) => {
    res.json(getBotState());
  });

  app.get("/api/bot/qr", async (req, res) => {
    const { qrCode } = getBotState();
    if (!qrCode) {
      return res.status(404).json({ error: "No active QR code. Start the live connection first." });
    }
    try {
      const qrUrl = await QRCode.toDataURL(qrCode, { margin: 2, width: 250 });
      res.json({ qrUrl });
    } catch (error: any) {
      res.status(500).json({ error: "Failed to generate QR code image." });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Start / Stop Live Bot
  // ---------------------------------------------------------------------------
  app.post("/api/bot/start", (req, res) => {
    startLiveBot(true);
    res.json({ success: true, message: "Live bot start triggered." });
  });

  app.post("/api/bot/stop", (req, res) => {
    stopLiveBot();
    res.json({ success: true, message: "Live bot stop triggered." });
  });

  // ---------------------------------------------------------------------------
  // API: Clear Logs
  // ---------------------------------------------------------------------------
  app.post("/api/bot/clear-auth", (req, res) => {
    try {
      if (fs.existsSync("nebula_auth_info")) {
        fs.rmSync("nebula_auth_info", { recursive: true, force: true });
      }
      res.json({ success: true, message: "Session auth cache cleared." });
    } catch (e: any) {
      res.status(500).json({ success: false, error: e.message || "Failed to clear auth" });
    }
  });

  // Pairing code endpoint (Baileys native)
  app.post("/api/bot/pair", async (req, res) => {
    try {
      const rawPhone = (req.body && req.body.phone ? req.body.phone.toString() : "").replace(/\D/g, "");
      if (!rawPhone || rawPhone.length < 10 || rawPhone.length > 15) {
        return res.status(400).json({ success: false, error: "Valid E.164 phone number required (digits only, no +). Example: 6288888888888" });
      }
      const { state, saveCreds } = await useMultiFileAuthState("nebula_auth_info");
      if (!pairingSock || pairingSock.end) {
        pairingRequested = false;
        pairingSock = makeWASocket({
          auth: state,
          printQRInTerminal: false,
          logger: pino({ level: "silent" }),
          browser: (require("@whiskeysockets/baileys").Browsers || { macOS: () => ({ name: "Nebula", version: "1.0", vendor: "Nebula" }) }).macOS("Chrome"),
        });
        pairingSock.ev.on("creds.update", saveCreds);
      }
      if (state.creds && state.creds.registered) {
        return res.json({ success: true, message: "Already registered — pairing not needed.", registered: true });
      }
      const code = await new Promise((resolve, reject) => {
        const timeout = setTimeout(() => reject(new Error("Pairing timeout — connection did not reach connecting state within 15s.")), 15000);
        const listener = async (update) => {
          const connection = update && update.connection ? update.connection : null;
          if (connection === "connecting" && !(pairingSock.authState && pairingSock.authState.creds && pairingSock.authState.creds.registered) && !pairingRequested) {
            pairingRequested = true;
            clearTimeout(timeout);
            try {
              const pairCode = await pairingSock.requestPairingCode(rawPhone);
              resolve(pairCode);
            } catch (e) { reject(new Error("Pairing code request failed: " + (e && e.message ? e.message : e))); }
            pairingSock.ev.off("connection.update", listener);
          }
        };
        pairingSock.ev.on("connection.update", listener);
      });
      res.json({ success: true, code: code, phone: rawPhone, message: "Enter this code on WhatsApp: Settings → Linked Devices → Link a Device → Link with phone number instead" });
    } catch (e) {
      console.error("[Pair] Error:", e && e.message ? e.message : e);
      res.status(500).json({ success: false, error: e && e.message ? e.message : "Pairing failed." });
    }
  });


  app.post("/api/bot/clear-logs", (req, res) => {
    clearLogs();
    res.json({ success: true });
  });

  // ---------------------------------------------------------------------------
  // API: Command Simulation Playground
  // ---------------------------------------------------------------------------
  app.post("/api/bot/simulate", async (req, res) => {
    const { senderName, text } = req.body;
    if (typeof text !== "string" || !text.trim()) {
      return res.status(400).json({ error: "Message text is required." });
    }
    if (text.length > 2000) {
      return res.status(400).json({ error: "Message text is too long (max 2000 characters)." });
    }
    const cleanSenderName = typeof senderName === "string" ? senderName.trim().slice(0, 40) : "Guest User";
    const result = await simulateMessage(cleanSenderName || "Guest User", text);
    res.json(result);
  });

  // ---------------------------------------------------------------------------
  // API: List Commands (deduplicated by the registry)
  // ---------------------------------------------------------------------------
  app.get("/api/bot/commands", (req, res) => {
    const commands = getCommands().map(cmd => ({
      name: cmd.name,
      category: cmd.category,
      description: cmd.description,
      usage: cmd.usage || cmd.name,
      aliases: cmd.aliases || [],
    }));
    res.json(commands);
  });

  // ---------------------------------------------------------------------------
  // API: Get command usage analytics
  // ---------------------------------------------------------------------------
  app.get("/api/bot/analytics", (req, res) => {
    res.json({ stats: getCommandStats() });
  });

  // ---------------------------------------------------------------------------
  // API: Get details or code of a single command
  // ---------------------------------------------------------------------------
  app.get("/api/bot/commands/:name", (req, res) => {
    const cmdName = req.params.name.toLowerCase();
    const cmd = getCommand(cmdName);
    if (!cmd) {
      return res.status(404).json({ error: "Command not found." });
    }

    // Attempt to read the physical code file
    const filePath = path.join(getCommandsDir(), `${cmdName}.ts`);

    let code = "";
    if (fs.existsSync(filePath)) {
      code = fs.readFileSync(filePath, "utf-8");
    } else {
      // Return structured representation if file not on disk
      code = `import { BotCommand } from "../types.js";\n\n// Autogenerated dynamic code fallback\nconst cmd: BotCommand = {\n  name: "${cmd.name}",\n  category: "${cmd.category}",\n  description: "${cmd.description}",\n  execute: async (sock, msg, context) => {\n    await context.reply("Hello from ${cmd.name}!");\n  }\n};\nexport default cmd;`;
    }

    res.json({
      ...cmd,
      code
    });
  });

  // ---------------------------------------------------------------------------
  // API: Save or Create a command file
  // ---------------------------------------------------------------------------
  app.post("/api/bot/commands/save", async (req, res) => {
    const { name, code } = req.body;
    if (typeof name !== "string" || typeof code !== "string" || !code.trim()) {
      return res.status(400).json({ error: "Name and code are required." });
    }
    if (code.length > 100_000) {
      return res.status(400).json({ error: "Command code is too large (max 100KB)." });
    }

    const cleanName = name.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
    if (!cleanName) {
      return res.status(400).json({ error: "Invalid command name: use letters and digits only." });
    }

    const commandsDir = getCommandsDir();
    if (!fs.existsSync(commandsDir)) {
      fs.mkdirSync(commandsDir, { recursive: true });
    }

    const filePath = path.join(commandsDir, `${cleanName}.ts`);

    try {
      fs.writeFileSync(filePath, code, "utf-8");
      addLog(`📝 Saved command file: /src/bot/commands/${cleanName}.ts`);

      // Compile a self-contained artifact so production Node can load it too.
      await compileCommandToMjs(cleanName, filePath);

      // Reload the registry so the command becomes active immediately
      await initRegistry();
      const loaded = !!getCommand(cleanName);

      res.json({
        success: true,
        message: loaded
          ? `Command "${cleanName}" saved and loaded.`
          : `Command "${cleanName}" saved, but could not be loaded. Check the server logs.`,
        loaded,
      });
    } catch (error: any) {
      res.status(500).json({ error: `Failed to save command: ${error.message}` });
    }
  });

  // ---------------------------------------------------------------------------
  // API: AI-Powered Command Builder (using Gemini)
  // ---------------------------------------------------------------------------
  app.post("/api/bot/commands/generate", async (req, res) => {
    const { prompt, commandName, category, description } = req.body;

    if (typeof prompt !== "string" || !prompt.trim() || typeof commandName !== "string" || !commandName.trim()) {
      return res.status(400).json({ error: "Prompt and commandName are required." });
    }
    if (prompt.length > 4000) {
      return res.status(400).json({ error: "Prompt is too long (max 4000 characters)." });
    }

    // Security Guardrail: Prevent prompt injection or generation of unsafe server execution APIs
    const lowerPrompt = prompt.toLowerCase();
    const maliciousPatterns = [
      "ignore previous instructions",
      "ignore the instructions",
      "ignore original guidelines",
      "system commands",
      "child_process",
      "exec(",
      "execsync",
      "spawn(",
      "fs.unlink",
      "fs.rmdir",
      "rm -rf"
    ];
    const isSuspicious = maliciousPatterns.some(pattern => lowerPrompt.includes(pattern));
    if (isSuspicious) {
      addLog(`🛡️ [Guardrail] Blocked suspicious generation prompt targeting "${commandName}": Injection or unsafe system patterns detected.`);
      return res.status(400).json({ error: "Security Guardrail: Prompt contains content that violates safe dynamic generation guidelines." });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === "MY_GEMINI_API_KEY" || apiKey.trim() === "") {
      return res.status(400).json({ error: "Gemini API key is not configured. Please add it to Settings > Secrets." });
    }

    const cleanName = commandName.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
    if (!cleanName) {
      return res.status(400).json({ error: "Invalid command name: use letters and digits only." });
    }
    const cleanCategory = (typeof category === "string" ? category : "Utility").trim().slice(0, 40);
    const cleanDesc = (typeof description === "string" ? description : `Dynamic AI-generated command for ${cleanName}`).trim().slice(0, 200);

    addLog(`🤖 Asking Gemini to design command: "${cleanName}" (${prompt})`);

    try {
      const aiPrompt = `
Generate a fully functional TypeScript WhatsApp command file for a Baileys bot.
The file must export a default object implementing the following interface:

interface BotCommand {
  name: string;
  category: string;
  description: string;
  usage?: string;
  execute: (sock: any, msg: any, context: {
    sender: string;
    senderName: string;
    isOwner: boolean;
    isAdmin: boolean;
    prefix: string;
    commandName: string;
    args: string[];
    fullMessage: string;
    reply: (text: string, mediaUrl?: string) => Promise<any>;
    react: (emoji: string) => Promise<any>;
    downloadMedia?: () => Promise<Buffer | null>;
  }) => Promise<void> | void;
}

The command name is: "${cleanName}"
The category is: "${cleanCategory}"
The description is: "${cleanDesc}"
Specific instructions for what the command should do: "${prompt}"

Make the logic clean, fully typed, and robust. Always use markdown formatting in text outputs for neat messaging layout (e.g. bold like *text*, italics like _text_). If you use external API fetches, handle errors cleanly with try-catch and output helpful error messages. Use standard ES Module imports, specifically relative importing of the BotCommand type if needed, e.g. import { BotCommand } from "../types.js";

IMPORTANT: Output ONLY the raw TypeScript code. No markdown wrapping (like \`\`\`typescript ... \`\`\`), no conversational intros. Just raw TS code so I can save it directly to a file.
`;

      const codeRaw = await generateTextWithFallback(aiPrompt, undefined, "gemini-3.7-flash");
      let code = codeRaw || "";

      // Safety: strip markdown wraps if Gemini returned them despite instructions
      if (code.includes("```typescript")) {
        code = code.split("```typescript")[1].split("```")[0];
      } else if (code.includes("```ts")) {
        code = code.split("```ts")[1].split("```")[0];
      } else if (code.includes("```")) {
        code = code.split("```")[1].split("```")[0];
      }

      code = code.trim();

      // Save the file
      const commandsDir = getCommandsDir();
      if (!fs.existsSync(commandsDir)) {
        fs.mkdirSync(commandsDir, { recursive: true });
      }
      const filePath = path.join(commandsDir, `${cleanName}.ts`);
      fs.writeFileSync(filePath, code, "utf-8");

      // Compile and reload so the command is active immediately
      await compileCommandToMjs(cleanName, filePath);
      await initRegistry();
      const loaded = !!getCommand(cleanName);

      addLog(`✨ AI generated & successfully loaded command: /src/bot/commands/${cleanName}.ts`);

      res.json({
        success: true,
        message: loaded
          ? `Command "${cleanName}" created and loaded successfully!`
          : `Command "${cleanName}" created, but could not be loaded. Check the server logs.`,
        code,
        loaded,
      });
    } catch (error: any) {
      addLog(`❌ AI Command Generation failed: ${error.message}`);
      res.status(500).json({ error: `AI generation failed: ${error.message}` });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Download complete ready-to-run bot package as a ZIP!
  // ---------------------------------------------------------------------------
  const CONFIG_IMPORT_RE = /import\s+({[^}]+})\s+from\s+['"]\.\.\/config\.js['"];?/g;
  const CONFIG_SHIM = "const config = require('../config.json');\nconst getConfig = () => config;\nconst updateConfig = () => {};";

  function regexTranspile(source: string): string {
    let js = source;
    // Type-only imports (safe to drop)
    js = js.replace(/import\s+[^;]+?\s+from\s+['"]\.\.\/types\.js['"];?/g, "");
    // Project helper imports (resolved to root-level lib files in the zip)
    js = js.replace(/import\s+({[^}]+})\s+from\s+['"]\.\.\/geminiClient\.js['"];?/g, "const $1 = require('./geminiClient.js');");
    js = js.replace(/import\s+({[^}]+})\s+from\s+['"]\.\.\/database\.js['"];?/g, "const $1 = require('./database.js');");
    // Named imports from npm / other modules
    js = js.replace(/import\s+({[^}]+})\s+from\s+["']@google\/genai["'];?/g, "const $1 = require('@google/genai');");
    js = js.replace(/import\s+({[^}]+})\s+from\s+["']([^"']+)["'];?/g, "const $1 = require('$2');");
    js = js.replace(/import\s+([A-Za-z_$][\w$]*)\s+from\s+["']([^"']+)["'];?/g, "const $1 = require('$2');");
    // Exports and TS-only syntax
    js = js.replace(/export\s+default\s+(\w+);?/g, "module.exports = $1;");
    js = js.replace(/export\s+interface\s+\w+\s*\{[^}]*\}/g, "");
    js = js.replace(/export\s+const\s+(\w+)(:\s*[\w<>|'"]+)?\s*=/g, "const $1 =");
    js = js.replace(/export\s+async\s+function\s+(\w+)/g, "async function $1");
    js = js.replace(/export\s+function\s+(\w+)/g, "function $1");
    js = js.replace(/const\s+(\w+):\s*BotCommand\s*=/g, "const $1 =");
    js = js.replace(/:\s*BotCommand\b/g, "");
    js = js.replace(/:\s*BotCommandContext\b/g, "");
    return js;
  }

  /**
   * Converts a TypeScript source file to CommonJS for the exported package.
   * Prefers esbuild (handles all TS syntax correctly); falls back to a
   * conservative regex transpiler when esbuild is unavailable.
   */
  async function transpileTsToCjs(source: string): Promise<string> {
    // Rewrite config.ts imports to read the packaged config.json.
    const preprocessed = source.replace(CONFIG_IMPORT_RE, CONFIG_SHIM);
    try {
      const { transform } = await import("esbuild");
      const result = await transform(preprocessed, {
        loader: "ts",
        format: "cjs",
        platform: "node",
        target: "node18",
      });
      return result.code;
    } catch (e: any) {
      console.warn("[ZIP] esbuild transform unavailable; using regex transpiler:", e?.message || e);
      return regexTranspile(preprocessed);
    }
  }

  app.get("/api/bot/download-zip", async (req, res) => {
    addLog("📦 Packaging Nebula Bot for local download...");

    try {
      const zip = new AdmZip();

      // 1. Generate local start file: index.js
      const indexJs = `/**
 * Nebula Bot Local Startup File
 * Powered by @whiskeysockets/baileys
 */

const { default: makeWASocket, useMultiFileAuthState, DisconnectReason, fetchLatestBaileysVersion } = require("@whiskeysockets/baileys");
const pino = require("pino");
let pairingSock = null;
let pairingRequested = false;
const { Boom } = require("@hapi/boom");
const dotenv = require("dotenv");
const path = require("path");
const fs = require("fs");

dotenv.config();

const config = require("./config.json");

// Command Registry
const commands = new Map();

function loadCommands() {
  const commandsDir = path.join(__dirname, "commands");
  if (!fs.existsSync(commandsDir)) return;
  
  const files = fs.readdirSync(commandsDir);
  for (const file of files) {
    if (!file.endsWith(".js")) continue;
    try {
      const cmdPath = path.join(commandsDir, file);
      delete require.cache[require.resolve(cmdPath)];
      const cmd = require(cmdPath);
      // Support both ES default and CJS exports
      const command = cmd.default || cmd;
      if (command && command.name) {
        commands.set(command.name.toLowerCase(), command);
        console.log(\`🔮 Loaded command: \${command.name}\`);
      }
    } catch (err) {
      console.error(\`❌ Failed to load command file \${file}:\`, err.message);
    }
  }
  // Expose registered commands list globally for menu
  global.botCommands = Array.from(commands.values());
}

async function startBot() {
  console.log("🌌 Starting Nebula Bot...");
  loadCommands();

  const { state, saveCreds } = await useMultiFileAuthState("auth_session");
  const { version } = await fetchLatestBaileysVersion();

  const sock = makeWASocket({
    version,
    auth: state,
    printQRInTerminal: true, // Output QR in terminal for easy local scanning
    logger: pino({ level: "info" }),
    browser: ["Nebula Local", "Chrome", "1.0.0"],
  });

  sock.ev.on("connection.update", (update) => {
    const { connection, lastDisconnect, qr } = update;
    if (connection === "open") {
      console.log("✅ Nebula Bot connected successfully! Type .menu in chat to start.");
    }
    if (connection === "close") {
      const shouldReconnect = (lastDisconnect.error instanceof Boom) ? lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut : true;
      console.log(\`❌ Connection closed. Reconnecting: \${shouldReconnect}\`);
      if (shouldReconnect) {
        startBot();
      }
    }
  });

  sock.ev.on("creds.update", saveCreds);

  sock.ev.on("messages.upsert", async (m) => {
    if (m.type !== "notify") return;
    for (const msg of m.messages) {
      if (!msg.message || msg.key.fromMe) continue;

      const text = msg.message.conversation || 
                   msg.message.extendedTextMessage?.text || 
                   msg.message.imageMessage?.caption || 
                   msg.message.videoMessage?.caption || 
                   "";

      const prefix = config.prefix;
      if (!text.startsWith(prefix)) continue;

      const senderJid = msg.key.remoteJid;
      const senderNumber = senderJid.split("@")[0];
      const senderName = msg.pushName || "User";

      const body = text.slice(prefix.length).trim();
      const args = body.split(/\\s+/);
      const commandName = args.shift().toLowerCase();

      const command = commands.get(commandName);
      if (!command) continue;

      const isOwner = senderNumber === config.ownerNumber.replace(/[^0-9]/g, "");

      const context = {
        sender: senderJid,
        senderName,
        isOwner,
        isAdmin: isOwner, // local runner treats the owner as admin
        prefix,
        commandName,
        args,
        fullMessage: text,
        reply: async (textStr, mediaUrl) => {
          if (mediaUrl) {
            return await sock.sendMessage(senderJid, { image: { url: mediaUrl }, caption: textStr }, { quoted: msg });
          }
          return await sock.sendMessage(senderJid, { text: textStr }, { quoted: msg });
        },
        react: async (emoji) => {
          return await sock.sendMessage(senderJid, { react: { text: emoji, key: msg.key } });
        }
      };

      try {
        await command.execute(sock, msg, context);
      } catch (err) {
        console.error(\`Error in \${commandName}:\`, err);
        context.reply(\`❌ Error in \${commandName}: \` + err.message);
      }
    }
  });
}

startBot();
`;

      // 2. Generate package.json for local
      const packageJson = {
        name: "nebula-bot-local",
        version: "1.1.0",
        description: "Nebula Bot - Lightweight WhatsApp Multi-Device Bot",
        main: "index.js",
        scripts: {
          start: "node index.js",
        },
        dependencies: {
          "@whiskeysockets/baileys": "^6.7.9",
          "@hapi/boom": "^10.0.1",
          "pino": "^9.0.0",
          "dotenv": "^16.4.5",
          "@google/genai": "^2.4.0"
        }
      };

      // 3. Generate README.md
      const readmeMd = `# 🌌 Nebula Bot - WhatsApp Multi-Device

A highly lightweight and modular WhatsApp Multi-Device Bot.

## 🚀 Quick Local Installation

1. Make sure you have **Node.js 18 or newer** installed.
2. Extract the downloaded ZIP file into a clean folder.
3. Open your terminal in the extracted folder and run:
   \`\`\`bash
   npm install
   \`\`\`
4. Configure your environment variables in \`.env\`:
   \`\`\`env
   GEMINI_API_KEY="YOUR_API_KEY_HERE"
   \`\`\`
5. Start the bot:
   \`\`\`bash
   npm start
   \`\`\`
6. A WhatsApp QR Code will print in your terminal. Scan it using **Linked Devices** on your phone!

## 🔮 Customization & Commands

- **Config File:** Edit \`config.json\` to customize prefix, bot name, bot image, and channel details.
- **Add Features:** All commands are loaded dynamically from the \`commands/\` folder. To create a new command, just add a new \`.js\` file into the \`commands/\` folder exporting a command structure!
- **Admin commands** (\`antilink\`, \`antitag\`, \`hidetag\`) are available to the owner in this local runner.

## ⚠️ Security Note

The \`.env\` file contains a placeholder API key. Set your real \`GEMINI_API_KEY\` before using AI features. Never share your \`.env\` or \`auth_session/\` folder.
`;

      // Add files to Zip
      zip.addFile("index.js", Buffer.from(indexJs), "Main local runner");
      zip.addFile("package.json", Buffer.from(JSON.stringify(packageJson, null, 2)), "Dependencies list");
      zip.addFile("config.json", Buffer.from(JSON.stringify(getConfig(), null, 2)), "Custom configuration settings");
      zip.addFile("README.md", Buffer.from(readmeMd), "Documentation");

      // Environment template — NEVER embeds the live API key.
      const localEnv = `GEMINI_API_KEY="MY_GEMINI_API_KEY"\n# Set your real Gemini API key here to enable AI features.\n`;
      zip.addFile(".env", Buffer.from(localEnv), "Environment configuration");

      // Shared runtime modules used by the commands (transpiled to CJS).
      for (const libFile of ["geminiClient.ts", "database.ts"]) {
        const libPath = path.join(process.cwd(), "src", "bot", libFile);
        if (fs.existsSync(libPath)) {
          const jsContent = await transpileTsToCjs(fs.readFileSync(libPath, "utf-8"));
          zip.addFile(libFile.replace(".ts", ".js"), Buffer.from(jsContent), "Shared runtime module");
        }
      }

      // Copy command files into ZIP (TypeScript -> CommonJS)
      const commandsDir = getCommandsDir();
      if (fs.existsSync(commandsDir)) {
        const files = fs.readdirSync(commandsDir);
        for (const file of files) {
          if (!file.endsWith(".ts")) continue;
          const filePath = path.join(commandsDir, file);
          const jsContent = await transpileTsToCjs(fs.readFileSync(filePath, "utf-8"));
          zip.addFile(`commands/${file.replace(".ts", ".js")}`, Buffer.from(jsContent), "Command logic file");
        }
      }

      const zipBuffer = zip.toBuffer();

      res.set({
        "Content-Type": "application/zip",
        "Content-Disposition": "attachment; filename=nebula-bot-local.zip",
        "Content-Length": zipBuffer.length
      });

      res.send(zipBuffer);
      addLog("✅ Nebula Bot ZIP compiled and sent to user successfully!");
    } catch (error: any) {
      addLog(`❌ Failed to compile ZIP download: ${error.message}`);
      res.status(500).json({ error: `ZIP packing failed: ${error.message}` });
    }
  });

  // ---------------------------------------------------------------------------
  // API: Audio Transcription using Gemini with fallback models
  // ---------------------------------------------------------------------------
  const ALLOWED_AUDIO_MIMES = [
    "audio/webm", "audio/mp4", "audio/mpeg", "audio/mp3",
    "audio/ogg", "audio/wav", "audio/x-wav", "audio/aac", "audio/x-m4a",
  ];
  const MAX_AUDIO_BASE64 = 30_000_000; // ~22 MB of binary audio

  app.post("/api/gemini/transcribe", async (req, res) => {
    const { audioBase64, mimeType } = req.body;
    if (typeof audioBase64 !== "string" || !audioBase64) {
      return res.status(400).json({ error: "Missing audioBase64 payload" });
    }
    if (audioBase64.length > MAX_AUDIO_BASE64) {
      return res.status(413).json({ error: "Audio payload too large (max ~22MB of audio)." });
    }
    const mime = (typeof mimeType === "string" ? mimeType : "audio/webm").toLowerCase();
    if (!ALLOWED_AUDIO_MIMES.includes(mime)) {
      return res.status(400).json({ error: `Unsupported audio mime type "${mime}".` });
    }

    const ai = getAIClient();
    if (!ai) {
      return res.status(400).json({ error: "Gemini API key is not configured. Please add it to Settings > Secrets." });
    }

    const transcriptionModels = ["gemini-3.5-flash", "gemini-2.5-flash", "gemini-1.5-flash"];
    let lastError: any = null;

    for (const model of transcriptionModels) {
      try {
        const response = await ai.models.generateContent({
          model,
          contents: [
            {
              inlineData: {
                data: audioBase64,
                mimeType: mime,
              },
            },
            { text: "Accurately transcribe this audio message. Output only the plain transcription, no extra commentary, preambles, or punctuation headers." },
          ],
        });

        if (response && response.text) {
          return res.json({ transcript: response.text.trim() });
        }
      } catch (err: any) {
        console.warn(`⚠️ Transcription failed on model [${model}]:`, err?.message || err);
        lastError = err;
      }
    }

    res.status(500).json({ error: `Transcription failed across all fallback models: ${lastError?.message || lastError}` });
  });

  // ---------------------------------------------------------------------------
  // API: Real-time Voice Conversation using Gemini with fallbacks and TTS
  // ---------------------------------------------------------------------------
  app.post("/api/gemini/voice-conversation", async (req, res) => {
    const { prompt } = req.body;
    if (typeof prompt !== "string" || !prompt.trim()) {
      return res.status(400).json({ error: "Missing prompt query" });
    }
    if (prompt.length > 5000) {
      return res.status(400).json({ error: "Prompt is too long (max 5000 characters)." });
    }

    const ai = getAIClient();
    if (!ai) {
      return res.status(400).json({ error: "Gemini API key is not configured. Please add it to Settings > Secrets." });
    }

    try {
      // 1. Generate textual spoken reply using robust text fallback generator helper
      const replyText = await generateTextWithFallback(
        prompt,
        "You are a friendly, helpful, highly conversational AI voice assistant. Keep your responses super short (1-2 sentences), sweet, warm, and direct. Avoid asterisks, bullets, lists, markdown formatting, or emojis since your response will be read aloud.",
        "gemini-3.5-flash"
      );

      // 2. Synthesize spoken reply to audio using TTS preview model
      let audioBase64: string | null = null;
      try {
        const speechResponse = await ai.models.generateContent({
          model: "gemini-3.1-flash-tts-preview",
          contents: [{ parts: [{ text: replyText }] }],
          config: {
            responseModalities: ["AUDIO"],
            speechConfig: {
              voiceConfig: {
                prebuiltVoiceConfig: { voiceName: "Zephyr" },
              },
            },
          },
        });
        audioBase64 = speechResponse.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data || null;
      } catch (ttsErr: any) {
        console.warn("⚠️ TTS audio synthesis rate-limited or busy. Falling back to text-only spoken reply.", ttsErr?.message || ttsErr);
      }

      res.json({
        text: replyText,
        audioBase64
      });
    } catch (error: any) {
      console.error("Voice conversation error:", error);
      res.status(500).json({ error: error.message || error });
    }
  });

  // JSON body / payload error handling as clean JSON instead of HTML
  app.use((err: any, req: Request, res: Response, next: NextFunction) => {
    if (err?.type === "entity.too.large") {
      return res.status(413).json({ error: "Request body too large." });
    }
    if (err?.type === "entity.parse.failed") {
      return res.status(400).json({ error: "Invalid JSON body." });
    }
    next(err);
  });

  return app;
}
